fix CI/CD

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,6 +3,11 @@ on: [push]
 jobs:
   Coverage:
     runs-on: ubuntu-latest
+    services:
+      redis:
+        image: redis:latest
+        ports:
+          - 6379:6379
     steps:
       - uses: actions/checkout@v4
 
@@ -27,6 +32,19 @@ jobs:
 
       - name: Set up environment
         run: echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
+
+      - name: Wait for Redis to be ready
+        run: |
+            for i in {1..10}; do
+              if nc -z localhost 6379; then
+                echo "Redis is up!"
+                exit 0
+              fi
+              echo "Waiting for Redis..."
+              sleep 1
+            done
+            echo "Redis failed to start"
+            exit 1
 
       - name: Code Climate Coverage Action
         uses: paambaati/codeclimate-action@v9.0.0
